### ISSUE TITLE
dumping failed @ mysql 5.6.26 + rails 5.0

### ISSUE THREAD

**Issue by RainThinks** [yamldb/yaml_db#109]
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key LIMIT 1000 OFFSET 0' at line 1: SELECT  * FROM `ar_internal_metadata` ORDER BY key LIMIT 1000 OFFSET 0

I think key is a keyword in mysql, the column name should be quoted.

SELECT  * FROM `ar_internal_metadata` ORDER BY `key` LIMIT 1000 OFFSET 0

**Comment by dnrce** [comment]
@RainThinks, thanks for reporting. Can you please test the fix in #110?

**Comment by RainThinks** [comment]
testing passed.

thanks for quick response.

**Comment by martini** [comment]
Also testing passed here.

**Comment by stoffie** [comment]
I ran this on my server and it works! Great work

**Comment by JakeTheSnake3p0** [comment]
Any chance of pushing this through?

**Comment by dnrce** [comment]
Haven't merged due to test failures. I'll see if I can get them sorted.

**Comment by dnrce** [comment]
I've rebased the fix to include the latest HABTM changes and got the tests to pass. Anyone mind doing a final re-test before I merge?

**Comment by JakeTheSnake3p0** [comment]
I just did a test off of your branch and it's working.

**Comment by dnrce** [comment]
Thanks @JakeTheSnake3p0!

**Comment by dnrce** [comment]
Released yaml_db 0.5.0.
