### ISSUE TITLE
Can't use branch for Rails 2

### ISSUE THREAD

**Issue by jennyfong** [yamldb/yaml_db#22]
I've downloaded the rails 2 branch into the plugin directory but the following error is shown:

<pre>
 rake db:data:dump
(in /home/jfong/biorails/enterprise/trunk)
Configuring for Native RUBY
Compound Plugin: Biorails Demo Compound Inventory
rake aborted!
no such file to load -- rails/railtie
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- rails/railtie (MissingSourceFile)
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
	from /home/jfong/biorails/enterprise/trunk/vendor/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `require'
	from /home/jfong/biorails/enterprise/trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /home/jfong/biorails/enterprise/trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
	from /home/../trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /home/../trunk/vendor/plugins/yaml_db/lib/yaml_db.rb:6
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
	from /home/../trunk/vendor/gems/polyglot-0.3.1/lib/polyglot.rb:64:in `require'
	from /home/../trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /home../trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:547:in `new_constants_in'
	from /home/../trunk/vendor/rails/activesupport/lib/active_support/dependencies.rb:182:in `require'
	from /home/../trunk/vendor/plugins/yaml_db/init.rb:1:in `evaluate_init_rb'
	from /home../trunk/config/../vendor/rails/railties/lib/rails/plugin.rb:158:in `evaluate_init_rb'
	from /home../trunk/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
	from /home././trunk/config/../vendor/rails/railties/lib/rails/plugin.rb:154:in `evaluate_init_rb'
	from /home../trunk/config/../vendor/rails/railties/lib/rails/plugin.rb:48:in `load'
	from /home/../trunk/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:38:in `load_plugins'
	from /home/../trunk/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `each'
	from /home/../trunk/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `load_plugins'
	from /home/../trunk/config/../vendor/rails/railties/lib/initializer.rb:369:in `load_plugins'
	from /home/../trunk/config/../vendor/rails/railties/lib/initializer.rb:165:in `process'
	from /home/../trunk/config/../vendor/rails/railties/lib/initializer.rb:113:in `send'
	from /home/../trunk/config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
	from /home/../trunk/config/environment.rb:27
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /home/../vendor/rails/railties/lib/commands/about.rb:1
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from script/about:4
</pre>

I'm using Rails 2.3.9
<pre>
About your application's environment
Ruby version              1.8.7 (i486-linux)
RubyGems version          1.3.7
Rack version              1.1
Rails version             2.3.9
Active Record version     2.3.9
Active Resource version   2.3.9
Action Mailer version     2.3.9
Active Support version    2.3.9
Edge Rails revision       b492d494214a17f0050222ac724a65c8d0881805
Environment               development
Database adapter          mysql
</pre>

I have also tried to use the master as a plugin as some of the commits mentioned that it can be used as a plugin in Rails 2, but both gave me the same error. Is it something obvious that I'm missing?

**Comment by dnrce** [comment]
Rails 2.x is no longer supported, as decided in #69.
