### ISSUE TITLE
Make it easier to load the tasks when using it as a Gem

### ISSUE THREAD

**Issue by pupeno** [yamldb/yaml_db#3]
Hello,

Could you please make it easier to use the rake tasks when using yaml_db as a Gem?

There's an easier way to allow rake tasks to be loaded when a library is used as a Gem instead of as a plug in. For thinking sphinx it's

require "thinking_sphinx/tasks"

in the Rakefile:

http://github.com/freelancing-god/thinking-sphinx/blob/master/lib/thinking_sphinx/tasks.rb

**Comment by dnrce** [comment]
Rails 2.x is no longer supported, as per #69.
