### ISSUE TITLE
Issues with incomplete dumps

### ISSUE THREAD

**Issue by AlbertGrimley** [yamldb/yaml_db#38]
Anyone else having an issue where dump files are incomplete?  I'm calling the gem directly from my rails app rather than using a rake task.  I am calling it exactly as the rake task does.  I ended up adding a flush and close after the dump and this solved my problem:  https://github.com/rgrimard/yaml_db/commit/e5c3f345c8ee7785b5e9e5b86b1f811c93ceee65

**Comment by dnrce** [comment]
Fixed by #79.
