### ISSUE TITLE
Rails 2.3.8 deprecation warning

### ISSUE THREAD

**Issue by anshul** [yamldb/yaml_db#5]
Rails 2.3.8 gives this:

    DEPRECATION WARNING: Rake tasks in vendor/plugins/yaml_db/tasks are deprecated. Use lib/tasks instead. (called from <top (required)> at ***/gems/rails-2.3.8/lib/tasks/rails.rb:10)

Also, are we rails 3 compatible yet?

**Comment by dnrce** [comment]
Rails 2.x is no longer supported, as per #69.
