### ISSUE TITLE
Option to dump or load a Single Table

### ISSUE THREAD

**Issue by ballin22s** [yamldb/yaml_db#76]
It would be great if you can add a way to limit a database dump or load to a single table by adding a table parameter to the rake task.

Ex. 
rake db:data:dump["table_name"]   ->   Dump contents of Rails database table "table_name" to db/data.yml
rake db:data:load["table_name"]   ->   Load contents of db/data.yml into the database table "table_name"

**Comment by kikicarbonell** [comment]
:+1:

**Comment by epaminond** [comment]
Would be usefull!

**Comment by glassputan** [comment]
Bump

**Comment by dnrce** [comment]
Consolidating under #9.
