### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by Supernats** [yamldb/yaml_db#86]
Is this project still being maintained? The last few issues have received no responses. There have been multiple attempts to add single table support that have fizzled with responses of "needs cleanup" but too general for the author to improve upon. What is the current state of the project?

**Comment by jrgifford** [comment]
It's not as maintained as it probably should be, but there are people who merge things when the need arises. At the moment, I don't personally use it anymore at work due to other reasons, and that has contributed to my no longer working on it often.
